server:
  port: 4000

auth:
  service:
    url: http://localhost:5004/auth

spring:
  cloud:
    gateway:
      routes:

        - id: product-service
          uri: http://localhost:5000
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1
            - JwtValidation

        - id: inventory-service
          uri: http://localhost:5001
          predicates:
            - Path=/api/inventory/**
          filters:
            - StripPrefix=1
            - JwtValidation

        - id: auth-service
          uri: http://localhost:5004
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

