server:
  port: 4000

spring:
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:5000
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1

