server:
  port: 4000

auth:
  service:
    url: lb://AUTH-SERVICE/auth

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:

        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**
          filters:
            - StripPrefix=1

        - id: category-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/category/**
          filters:
            - StripPrefix=1

        - id: inventory-service
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/api/inventory/**
          filters:
            - StripPrefix=1
            - JwtValidation

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1

        - id: order-service-order
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=1
            - JwtValidation

        - id: order-service-cart
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/cart/**
          filters:
            - StripPrefix=1
            - JwtValidation

      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:5173"
              - "http://localhost:3000"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka

