spring:
  application:
    name: product-service
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:product-service-db
    driver-class-name: org.h2.Driver
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

server:
  port: 5000

inventory:
  service:
    url: http://INVENTORY-SERVICE/inventory/stock

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
